### ISSUE TITLE
API Token Failed

### ISSUE THREAD

**Issue by johnharris85** [1000ch/pinput#14]
I've been using the extension with no issues for a few days and suddenly it's saying my API token has failed. I've regenerated a new token and uninstalled the extension but still gives me the same error. Are there any known bugs around this?

**Comment by 1000ch** [comment]
I have also confirmed sane error yesterday. But it seems to be API Server's error, 

https://twitter.com/Pinboard/status/556895203382931457

This problem is solved now, so Pinput works well now. :)

**Comment by johnharris85** [comment]
Ye there was nothing on the Twitter feed this morning but debugged the API response with Chrome's developer tools and saw it was the API down, rather than an extension bug :)
