### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by ryan-gallagher** [1000ch/pinput#15]
It seems the keyboard shortcut is CMD+B, not Control+B. This causes a conflict in that anytime I want to make text bold in a text editor in the browser, it opens the extension.

**Comment by aheckler** [comment]
Curious as to why this was closed, since this is also happening to me quite often. 

cc @1000ch

**Comment by 1000ch** [comment]
At first, I have an aim to set keyboard shortcut to open popup as <kbd>Command</kbd> + <kbd>B</kbd> in Mac. So description for it is wrong now.

I think that <kbd>Command</kbd> + <kbd>B</kbd> is instinctive. Is it OK to configure keyboard shortcut for this extension individually on `chrome://extensions/`. Or default one should be changed?

**Comment by aheckler** [comment]
> I think that Command + B is instinctive.

That might be true, but it also conflicts with a *very* common existing shortcut: bolding text. 

I think the option to configure it in the extension settings is the best way to go. Changing the default to Control + B might not solve anything, since then Windows users would face the same issue, right?

**Comment by 1000ch** [comment]
>I think the option to configure it in the extension settings is the best way to go. Changing the default to Control + B might not solve anything, since then Windows users would face the same issue, right?

Yes, I think so. I will **not** change shortcut for now, please change the shortcut for Pinput from bottom of `chrome://extensions/` page :(
