### ISSUE TITLE
Not auto-populating URL / Title anymore

### ISSUE THREAD

**Issue by johnharris85** [1000ch/pinput#22]
Don't know exactly when this happened, last couple of months maybe, but clicking the icon in the browser bar no longer auto-populates the URL and title in the popup?

**Comment by 1000ch** [comment]
Umm, I cannot, too :(
Please tell me if you detect the way to reproduce?

**Comment by johnharris85** [comment]
So I looked into this a little last night. It's a bit spotty about when it happens and when it doesn't. Think it has something to do with whether the URL in the bar is 'dirty' or not. So if I go to www.google.com/something/something-else and the page loads. Then I delete the /something-else and then try pinput it doesn't populate. I'll do more testing and let you know. I can't reproduce every time though.

**Comment by 1000ch** [comment]
>I'll do more testing and let you know.

Thank you for debugging. I will use this carefully, too.

**Comment by polm** [comment]
Just wanted to say this happens to me intermittently as well, on both Linux and Windows7. Sometimes all fields are blank, sometimes they're left over from another tab.

**Comment by 1000ch** [comment]
Would you try `v1.8.1` and issue again if have a problem? 
It includes an experimental change to use background page persistently.

**Comment by polm** [comment]
Since updating I don't think I've seen the issue with stale contents any more, thanks for the fix!
