### ISSUE TITLE
SyntaxError:  Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by eswat2** [1000ch/pinput#25]
started up Chrome this morning and i'm getting this error everytime i try to save a pin, any idea why this might be happening?

i went to pinboard and entered a pin manually, so that side seems to be working.

Here's what it looks like:

<img width="411" alt="screen shot 2016-10-11 at 8 41 51 am" src="https://cloud.githubusercontent.com/assets/334293/19277568/f476797e-8f8e-11e6-815d-8b427b5c6f13.png">

**Comment by eswat2** [comment]
Chrome:  Version 53.0.2785.143 (64-bit)
macOS Sierra: 10.12

**Comment by 1000ch** [comment]
Umm, I can't reproduce. Does anyone have this same errors?

**Comment by eswat2** [comment]
it just started working again, so it must have been something with the api service.  If the service call failed, it might be returning a page which would explain the token < in JSON at position 0

Closing
