### ISSUE TITLE
Uncaught TypeError: r.getClientRects is not a function

### ISSUE THREAD

**Issue by oppara** [1000ch/pinput#33]
When editing the tags, fired error of title.

Maybe the cause is https://github.com/1000ch/pinput/commit/e61363 
In my environment, I restored the version of jquery and confirmed behavior.

- pinput: 1.10.0
- chrome: 74.0.3729.169
- os: macOS 10.14.5

<img width="715" alt="typeError" src="https://user-images.githubusercontent.com/10661/59773170-2017a800-92e8-11e9-92b9-62548c655aa2.png">

**Comment by 1000ch** [comment]
Fixed on `v1.10.1`.
